force-app/main/default/objects/Debug_Log__e/Debug_Log__e.object-meta.xml
<CustomObject>
    <description>Platform event object to send debug logs from the DebugLog class. These can be captured by a lightning component for display to authorized users</description>
    <label>Debug Log</label>
    <pluralLabel>Debug Logs</pluralLabel>
</CustomObject>

force-app/main/default/objects/Debug_Log__e/fields/Caller__c.field-meta.xml
<CustomField>
    <fullName>Caller__c</fullName>
    <description>Name of the method that experienced the error</description>
    <label>Caller</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Debug_Log__e/fields/DebugData__c.field-meta.xml
<CustomField>
    <fullName>DebugData__c</fullName>
    <description>Error message</description>
    <label>DebugData</label>
    <length>10240</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Debug_Log__e/fields/EndPoint__c.field-meta.xml
<CustomField>
    <fullName>EndPoint__c</fullName>
    <description>REST endpoint that was called</description>
    <label>EndPoint</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Debug_Logger_Setting__mdt/Debug_Logger_Setting__mdt.object-meta.xml
<CustomObject>
    <description>Settings that control the operation of the debug_logger package</description>
    <label>Debug Logger Setting</label>
    <pluralLabel>Debug Logger Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Debug_Logger_Setting__mdt/fields/Publish_Events__c.field-meta.xml
<CustomField>
    <fullName>Publish_Events__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Indicates if the Debug_Log Platform Event should be published after saving the event in the log</description>
    <inlineHelpText>When set, will publish a Debug_Log Platform Event after saving the event in the log</inlineHelpText>
    <label>Publish Events</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DebugInfo__c/DebugInfo__c.object-meta.xml
<CustomObject>
    <description>Storage for Debug logs</description>
    <label>DebugInfo</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>DebugInfo Entry</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DebugInfos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DebugInfo__c/fields/Caller__c.field-meta.xml
<CustomField>
    <fullName>Caller__c</fullName>
    <description>Procedure that created the entry</description>
    <label>Caller</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DebugInfo__c/fields/DebugData__c.field-meta.xml
<CustomField>
    <fullName>DebugData__c</fullName>
    <label>DebugData</label>
    <length>10240</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/DebugInfo__c/fields/EndPoint__c.field-meta.xml
<CustomField>
    <fullName>EndPoint__c</fullName>
    <label>EndPoint</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DebugLog.cls
/*
  DebugLog class
  provides a method of saving logs in a custom object
 
  Methods:
  DebugLog(String CallerIdentification)
    CallerIdentification is a string that identifies the process that created the entry
  saveLog(String LogEntry)
    LogEntry is a string that provides the data to be logged
    can be called multiple times to append to the log
  commitLog(String LogEntry)
    LogEntry is a string that provides data to be logged
    Calling this method saves the data in the custom object and clears the log string
    (but leaves the CallerIdentification intact)   

    Marc D Behr    
*/

public with sharing class DebugLog {

	private String logData { set; get { if (logData == null) { logData = ''; } return logData; } }
	private string caller { set; get; }
    private Boolean publishEvent { set; get; }
	public string endPoint { public set; private get { if (endPoint == null) { endPoint = 'undefined'; } return endPoint; } }

 
	public DebugLog(String procedure) {
		caller = procedure;
        Debug_Logger_Setting__mdt[] localSettings = [Select Publish_Events__c from Debug_Logger_Setting__mdt where DeveloperName = 'Local'];
        if(null != localSettings) {
            publishEvent = true; // publish by default
        } else {
            publishEvent = localSettings[0].Publish_Events__c;
        }
	}

	public void saveLog(String entry) {
		logData += entry + '\n';
	}

	public void commitLog(String entry) {
		logData += entry + '\n';
		try {
			DebugInfo__c debugInfo = new DebugInfo__c(
                Caller__c = caller.abbreviate(SObjectType.DebugInfo__c.Fields.Caller__c.Length), 
                DebugData__c = obscurePasswords(logData).abbreviate(SObjectType.DebugInfo__c.Fields.DebugData__c.Length), 
                EndPoint__c = endPoint.abbreviate(SObjectType.DebugInfo__c.Fields.EndPoint__c.Length)
            );
			insert debugInfo;

            if (publishEvent) {
                // publish the platform event 
                Debug_Log__e debugEvent = new Debug_Log__e(
                    Caller__c = caller.abbreviate(SObjectType.Debug_Log__e.Fields.Caller__c.Length),
                    DebugData__c = obscurePasswords(logData).abbreviate(SObjectType.Debug_Log__e.Fields.DebugData__c.Length),
                    EndPoint__c = endPoint.abbreviate(SObjectType.Debug_Log__e.Fields.EndPoint__c.Length) 
                );
                system.debug(debugEvent);
                EventBus.publish(debugEvent);
            }
            
			logData = '';

		}

		catch(Exception e) {
			//silently ignore
			system.debug('Exception occurred: ' + e.getMessage());
		}
	}

	private string obscurePasswords(string input) {
		// replace any passwords with *'s in the logged messages
		return input.replaceAll('([pP]assword)=([^,\\s]+)\\s?', '$1=******');
	}
}