force-app/main/default/objects/DebugInfo__c/DebugInfo__c.object-meta.xml
<CustomObject>
    <description>Storage for Debug logs</description>
    <label>DebugInfo</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>DebugInfo Entry</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DebugInfos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DebugInfo__c/fields/DebugData__c.field-meta.xml
<CustomField>
    <fullName>DebugData__c</fullName>
    <label>DebugData</label>
    <length>10240</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/DebugCleanupTest.cls
/*
    debug_logger cleanup processor

    Tests the class that cleans old records from the system
    
    Marc D Behr
*/

@isTest
private class DebugCleanupTest {
	static list<DebugInfo__c> debugInfoList ;

	@TestSetup static void createRecords() {
		debugInfoList = new list<DebugInfo__c> ();

			for (integer i = 0; i < 200; i++) {
				debugInfoList.add(new DebugInfo__c(DebugData__c = 'Test ' + i));
			}
			insert debugInfoList;
	}

	static testMethod void  DebugLogsAreDeletedWhenBatchIsRun() {
		debugInfoList = [Select Id from DebugInfo__c];
		system.AssertEquals(200,debugInfoList.size());
		Test.startTest();
		Database.executeBatch(new DebugCleanup());
		Test.stopTest();
		debugInfoList = [Select Id from DebugInfo__c];
		system.AssertEquals(0,debugInfoList.size());
	}

}