force-app/main/default/objects/Debug_Logger_Setting__mdt/Debug_Logger_Setting__mdt.object-meta.xml
<CustomObject>
    <description>Settings that control the operation of the debug_logger package</description>
    <label>Debug Logger Setting</label>
    <pluralLabel>Debug Logger Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Debug_Logger_Setting__mdt/fields/Days_To_Keep__c.field-meta.xml
<CustomField>
    <fullName>Days_To_Keep__c</fullName>
    <defaultValue>5</defaultValue>
    <description>Logs that are more than the specified number of days since they were created are deleted when the DebugCleanup batch job runs</description>
    <label>Days To Keep</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DebugInfo__c/DebugInfo__c.object-meta.xml
<CustomObject>
    <description>Storage for Debug logs</description>
    <label>DebugInfo</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>DebugInfo Entry</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DebugInfos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DebugInfo__c/fields/Created_Time__c.field-meta.xml
<CustomField>
    <fullName>Created_Time__c</fullName>
    <defaultValue>Now()</defaultValue>
    <description>timestamp this entry was created</description>
    <label>Created Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/DebugCleanup.cls
/*
    debug_logger cleanup processor

    Cleans old records from the system
    
    Marc D Behr
*/

global  class DebugCleanup implements Database.batchable<sObject> {

     global Database.QueryLocator start(Database.BatchableContext BC) {
        Integer daysToKeep;
        if(Test.isRunningTest()) {
            daysToKeep = 2; // in the future to ensure that all logs will be deleted when running tests
        } else {
            // look for the local settings
            Debug_Logger_Setting__mdt[] localSettings = [Select Days_To_Keep__c from Debug_Logger_Setting__mdt where DeveloperName = 'Local'];
            if(null != localSettings) {
                daysToKeep = Integer.valueOf(-(localSettings[0].Days_To_Keep__c));
            } else {
                daysToKeep = -2; // default to 2 days ago
            }
        }

        String dateString = String.valueof(Date.today().adddays(daysToKeep)).substringBefore(' ')+'T00:00:00Z';
        system.debug('Selecting records before ' + dateString);

		String query = 'select id from debuginfo__c where Created_Time__c < '+dateString ;
        return Database.getQueryLocator(query);
     }

    global void execute(Database.BatchableContext BC, List<debuginfo__c> scope){
		delete scope;
		DataBase.emptyRecycleBin(scope);
    }

    global void finish(Database.BatchableContext BC)
    {
    }
}